# campuscare/pharmacy/migrations/0001_initial.py — Step 7
# Generated by Django 4.2.29 on 2026-03-27 12:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('consultation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DispenseRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('dispensed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('quota_signed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pharmacist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dispense_records', to='accounts.userprofile')),
                ('prescription', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dispense_record', to='consultation.prescription')),
            ],
            options={
                'verbose_name': 'Dispense record',
                'verbose_name_plural': 'Dispense records',
                'ordering': ['-dispensed_at'],
            },
        ),
    ]
