# campuscare/inventory/migrations/0001_initial.py — Step 8
# Generated by Django 4.2.29 on 2026-03-27 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('category', models.CharField(choices=[('general', 'General'), ('analgesic', 'Analgesic'), ('antibiotic', 'Antibiotic'), ('supplement', 'Supplement'), ('first_aid', 'First Aid')], default='general', max_length=20)),
                ('unit', models.CharField(choices=[('tablet', 'Tablet'), ('strip', 'Strip'), ('bottle', 'Bottle'), ('box', 'Box'), ('tube', 'Tube')], default='tablet', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Medicine',
                'verbose_name_plural': 'Medicines',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('season_tag', models.CharField(choices=[('general', 'General'), ('summer', 'Summer'), ('monsoon', 'Monsoon'), ('winter', 'Winter')], default='general', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('medicine', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='inventory.medicine')),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stock',
                'ordering': ['quantity', 'medicine__name'],
            },
        ),
    ]
